### ISSUE TITLE
Merging this chart into the WorkAdventure repo

### ISSUE THREAD

**Issue by moufmouf** [klauserber/workadventure-k8s#1]
Hey @klauserber !

Once more, thanks again for writing this chart.
Until recently, I was not using Helm. I've been testing it lately (and testing your chart), and it's great!

I'm strongly considering moving our own env to Helm and we would use your chart as a basis. There are a bunch of changes I'm planning to do though (regarding setting the number of replicas in the back servers in particular and adapting the env vars to 1.18.x).

Would you mind if we merge your repo in the /contrib/helm directory of the main WorkAdventure repository?

- I would of course keep the licence.
- We could change the chart at the same time we introduce changes (whenever new env vars or new services appear)
- We could run E2E tests on the chart with each change in WorkAdventure to ensure we don't break anything

We can give you rights to the workadventure/workadventure repo so you can continue working on the chart freely.

Also, if you are ok with this plan, I can do the merge myself, or you can do a PR if you want proper attribution of the commited files :)
Let me know what you think!

**Comment by klauserber** [comment]
Hi @moufmouf 

that is a very nice idea to have a official helm chart for WA and i am very glad to help out :-)

I will create a PR against the WorkAdventure repo in the next days.

And I will archive this repo with a link to the new location.

Would be nice, when you publish the chart to artifacthub.io like this: https://artifacthub.io/packages/helm/workadventure/workadventure

I think I don't need rights to the WA repo. If I have changes I create PR.

**Comment by moufmouf** [comment]
Woot!
Super nice!

I'll be on holiday next week so don't worry if I'm not answering straight away to your PR.

Thanks a lot!
